name: build-test

on:
  push:
    tags: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pdm install --dev
    - name: Lint check
      run: |
        pdm run flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
        pdm run flake8 tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Run tests
      run: |
        pdm run pytest
